settings:
  name: Speech Journal
  description: Content management for developmental psychology articles
  url: https://speechpsychology.com/
  locale: en

media:
  input: assets/images
  output: assets/images

content:
  - name: posts
    label: Articles
    type: collection
    path: _posts/
    filename: "{{primary}}.md"
    view:
      fields: [ title, date, author ]
      primary: title
      sort: [ date, title ]
      default:
        sort: date
        order: desc
    fields:
      - { name: layout, label: Layout, type: string, required: true, default: post }
      - { name: title, label: Title, type: string, required: true }
      - { name: date, label: Date, type: date, required: true }
      - { name: author, label: Author, type: list, required: true, default: [shivani] }
      - { name: categories, label: Categories, type: list }
      - { name: tags, label: Tags, type: list }
      - { name: download, label: Download, type: boolean, default: true }
      - { name: path, label: Path, type: string }
      - { name: open_access, label: Open Access, type: boolean, default: true }
      - { name: abstract, label: Abstract, type: rich-text, required: true, options: { maxlength: 500 } }
      - { name: body, label: Body, type: rich-text }

  - name: pages
    label: Other Pages
    type: collection
    path: _pages
    filename: "{{primary}}.md"
    view:
      fields: [ title, permalink ]
      primary: title
      sort: [ title ]
      default:
        sort: title
        order: asc
    fields:
      - { name: layout, label: Layout, type: string, required: true, default: page }
      - { name: title, label: Title, type: string, required: true }
      - { name: permalink, label: Permalink, type: string, required: true }
      - { name: body, label: Content, type: rich-text }

# Editor configuration
editor:
  preview: true

# Authentication (choose one method)
auth:
  # For GitHub authentication
  github:
    repo: The-Academic-Journal/website
    branch: main